#!/bin/sh
if [ ! $(id -u) -eq 0 ]; then
        echo "You need to run this command as root."
fi
if [ ! -f /boot/grub/grub.cfg ]; then
        echo "The file /boot/grub/grub.cfg does not exist."
        echo "Prior to runninng this command you should install grub and run either:"
        echo "update-grub"
        echo "or if this command does not exist:"
        echo "grub-mkconfig -o /boot/grub/grub.cfg"
fi
sed -n "/^[[:space:]]*\menuentry /s%[^']*'\([^']*\)'.*%\1%p" /boot/grub/grub.cfg > /tmp/list_boot_entries 
echo "

After booting, the boot menu will be displayed as above.
To navigate in the menu you will use the down and up arrow keys, then
press Enter to use the selected boot entry.

Press q then y to quit this display." >> /tmp/list_boot_entries
w3m  /tmp/list_boot_entries
