#!/bin/sh
. /etc/slapt-get/slapt-srcrc
cd $BUILDDIR
sed '
/SLACKBUILD REQUIRES:/{
s/ jdk /openjdk /gp
s/ jdk$/openjdk/gp
s/ six / python-six /gp
s/ six$/ python-six/gp
s/ python3-six/ python-six/gp
s/jack/jack-audio-connection-kit/gp
s/pygobject3-python3/py3gobject/gp
s/python3-Cython/Cython/gp
s/Pygments/Pygments py2Pygments/gp
s/docutils/docutils py2docutils/gp
s/pyxdg/pyxdg py3xdg/gp
s/lxml/python-lxml/gp
s/Markdown/python-markdown python2-markdown/gp
s/python3-pillow/python2-pillow python3-pillow/gp
s/python-distutils-extra/python2-distutils-extra/gp
s/gpusersoundfont/soundfont-generaluser/gp
s/python-distutils-extra/python2-distutils-extra python3-distutils-extra/gp
s/purple-telegram/telegram-purple/gp
s/tcl-tls/tls/gp
}' slackbuilds_data > bof
mv bof slackbuilds_data
